# Generated by Django 2.1.4 on 2019-11-07 09:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
